### ISSUE TITLE
"variant merging" documentation

### ISSUE THREAD

**Issue by smrgit** [googlegenomics/gcp-variant-transforms#112]
It would be great to have some more information about variant merging -- I have sometimes as many as 12 VCF files for a single tumor/normal pair and I'd like to understand how variants are merged.  I also noted that the main Google documentation page instructions suggests using ``--variant_merge_strategy MOVE_TO_CALLS`` while the documentation here on github doesn't mention that.  When I tried to import a set of 23 VCF files representing two tumor/normal pairs, I got the following error:
```
    ERROR:root:Exception at bundle <apache_beam.runners.direct.bundle_factory._Bundle object at 0x7f64a98d5450>, due to an exception.
     Traceback (most recent call last):
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 312, in call
        side_input_values)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/direct/executor.py", line 347, in attempt_call
        evaluator.process_element(value)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/direct/transform_evaluator.py", line 551, in process_element
        self.runner.process(element)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/common.py", line 390, in process
        self._reraise_augmented(exn)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/common.py", line 388, in process
        self.do_fn_invoker.invoke_process(windowed_value)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/common.py", line 281, in invoke_process
        self._invoke_per_window(windowed_value)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/common.py", line 307, in _invoke_per_window
        windowed_value, self.process_method(*args_for_process))
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/typehints/typecheck.py", line 63, in process
        return self.wrapper(self.dofn.process, args, kwargs)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/typehints/typecheck.py", line 81, in wrapper
        result = method(*args, **kwargs)
      File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/direct/helper_transforms.py", line 60, in process
        vi)
      File "gcp_variant_transforms/transforms/merge_headers.py", line 175, in add_input
        return self.merge_accumulators([source, to_merge])
      File "gcp_variant_transforms/transforms/merge_headers.py", line 180, in merge_accumulators
        self._header_merger.merge(merged_headers, to_merge)
      File "gcp_variant_transforms/transforms/merge_headers.py", line 127, in merge
        self._merge_header_fields(first.formats, second.formats)
      File "gcp_variant_transforms/transforms/merge_headers.py", line 160, in _merge_header_fields
        first_value, second_value, str(e)))
    ValueError: Incompatible number or types in header fields:OrderedDict([('id', 'GQ'), ('num', 1), ('type', 'Integer'), ('desc', 'Genotype Quality')]), OrderedDict([('id', 'GQ'), ('num', None), ('type', 'Integer'), ('desc', 'Conditional Phred-scaled genotype quality')])
    . Error: Incompatible numbers cannot be resolved: 1, None [while running 'MergeHeaders/MergeHeaders/CombinePerKey/LiftedCombinePerKey/ParDo(PartialGroupByKeyCombiningValues)']
```

I tried removing the ``--variant_merge_strategy MOVE_TO_CALLS`` option but I got the same error.

**Comment by nmousavi** [comment]
re error: This is due to an incompatible header data. Looks like 'GQ' field (Genotype Quality) is defined as a single Integer value in one VCF file, while another VCF file defines it as any-number (i.e., '.') of Integers. The pipeline fails because it doesn't know how to build the Bigquery schema in this case.

Solnution:
1) Make the definition of 'GQ' field consistent across the files. Or
2) Provide a representative header file that has a reference definition for all the fields (FORMAT, INFO, etc) using this flag 

--representative_header_file "gs://my_bucket/path/to/representative_header_file.vcf"


See this for more details 

https://github.com/googlegenomics/gcp-variant-transforms/blob/master/gcp_variant_transforms/options/variant_transform_options.py#L68

**Comment by arostamianfar** [comment]
To clarify: using --representative_header_file will not actually work in this case as explained in [the thread](https://groups.google.com/d/msg/google-genomics-discuss/r4_Kt2MITng/dViuGyIKCwAJ). This is b/c the parser still returns a single number for the GQ field while the 'correct' representation is to have a list. We realize it is frustrating to use Variant Transforms when dealing with malformed/incompatible VCF files, so we are actively working on automatically fixing such cases in Issue #101. In the meantime, changing the VCF header in all files to have Number='.' would work. You would also need to ensure that other fields (e.g. AD) are properly defined in all files.

RE documentation: Sorry for the delay on this! It has been on my TODO list and I have started on a draft. Should be ready by EOW. Also, tracked on Issue #76.
