### ISSUE TITLE
pip commands are failing after pip 10 upgrade

### ISSUE THREAD

**Issue by samanvp** [googlegenomics/gcp-variant-transforms#297]
with this error message:
> from pip import main ImportError: cannot import name 'main'

This is a known issue, following [these instructions](https://github.com/pypa/pip/issues/5221#issuecomment-382069604) solves the problem.

Also it seems running
`Running pip install --upgrade pip`
as root is prohibited and it's recommended to use `--user` whenever outside a venv. So we might want to update [our setup instructions](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/development_guide.md#setup-virtualenv).

Note in that case we need  the following line in our `.bashrc`:
`export PATH=${PATH}:$HOME/.local/bin`

**Comment by samanvp** [comment]
Following [Setup virtualenv](https://github.com/googlegenomics/gcp-variant-transforms/blob/master/docs/development_guide.md#setup-virtualenv) instructions on a clean GCE instance, I get the following after updating pip:
```
$ which pip 
/usr/bin/pip

$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ sudo pip install --upgrade pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 801kB/s 
Installing collected packages: pip
  Found existing installation: pip 9.0.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-18.1

$ which pip 
/usr/local/bin/pip

$ pip -V
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main

$ sudo pip -V
pip 18.1 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)
```

If I add `--user` to the pip upgrade command I get the following:
```
$ which pip
/usr/bin/pip

$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ sudo pip install --upgrade --user pip
Collecting pip
  Downloading https://files.pythonhosted.org/packages/c2/d7/90f34cb0d83a6c5631cf71dfe64cc1054598c843a92b400e55675cc2ac37/pip-18.1-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 829kB/s 
Installing collected packages: pip
Successfully installed pip-18.1

$ which pip
/usr/bin/pip

$ pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)

$ sudo pip -V
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
```
As one can see, in this case the pip version is still 9.0.1. Running pip upgrade command, without `sudo` in either or these forms also resulted in not updated pip version:
* `pip install --upgrade --user pip`
*  `pip install --upgrade pip`

It seems, in our case, following these [two advices](https://github.com/pypa/pip/issues/5221#issuecomment-382069604) does not result in desired state:
> * It's a good habit to use --user whenever outside a  venv
> * Never run pip with sudo unless you know what you're doing.
