### ISSUE TITLE
Add retries for errors from dataflow job status API

### ISSUE THREAD

**Issue by mbookman** [googlegenomics/gcp-variant-transforms#503]
I have an import of just over 4000 WGS samples running. The Dataflow job continues to run fine, but the underlying operation terminated early. I can see in the operation:

```
  - description: |-
      Stopped running "-c /opt/gcp_variant_transforms/bin/vcf_to_bq --region us-
central1 --zone us-central1-b --input_pattern <etc>: exit status 1: ge": "(fb3b7e06f4892fa9): Information about job 2019-07-11_18_02_38-5384807368573330751 could not be found in our system. Please double check the id is correct. If it is please contact customer support.",
          "status": "NOT_FOUND"
        }

      Traceback (most recent call last):
        File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
          "__main__", fname, loader, pkg_name)
        File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
          exec code in run_globals
        File "/opt/gcp_variant_transforms/src/gcp_variant_transforms/vcf_to_bq.py", line 508, in <module>
          run()
        File "/opt/gcp_variant_transforms/src/gcp_variant_transforms/vcf_to_bq.py", line 501, in run
          result.wait_until_finish()
        File "/opt/gcp_variant_transforms/venv/local/lib/python2.7/site-packages/apache_beam/runners/dataflow/dataflow_runner.py", line 1324, in wait_until_finish
          'Job did not reach to a terminal state after waiting indefinitely.')
      AssertionError: Job did not reach to a terminal state after waiting indefinitely.
```

This is probably a transient error from the Dataflow API. Not sure how often it happens, but it would be nice if `gcp_variant_transforms` was more robust to this.

**Comment by mbookman** [comment]
As a note, this happened a second time.

**Comment by allieychen** [comment]
[The bug](https://b.corp.google.com/issues/137693660) is file in Dataflow recently, I will track the issue and wait for a fix.

**Comment by kemp-google** [comment]
To elaborate: if a fix is going to be a very long way off we can try to work around it but it's not ideal - they are returning a permanent error so we shouldn't retry.  We'd need to look for the specific error string and retry a limited number of times (since the same error could be returned in an actual failure).

**Comment by allieychen** [comment]
Fixed in Dataflow.
